### ISSUE TITLE
Code Updating

### ISSUE THREAD

**Issue by alpacapatata** [IntroToCode/CodeMates6_Fall23#4]
## 💬 Discussion topic

Changes are not updated in the main branch

## ❗ Potential issues

There seems to be a lag between when branches are merged with the main code and when other users can see them

## 👥 People to consult

@SophonWhisperer @jainaman93 Any ideas why this is happening

## 📃 Details

Austin made changes that I was able to see 10 minutes ago but now they are gone. Potentially we don't have write access to the main code? Or its a server lag on my side?

**Comment by austinschoff** [comment]
tagging @nickchen and @austinschoff

**Comment by jainaman93** [comment]
Try it now. I have given write access

**Comment by austinschoff** [comment]
all set! thank you Aman!
*Austin P. Schoff*

MBA Candidate, Class of 2024
Haas School of Business
University of California, Berkeley
(310) 418-3495 | LinkedIn <https://www.linkedin.com/in/apschoff/>
