### ISSUE TITLE
Workstream 10/13

### ISSUE THREAD

**Issue by austinschoff** [IntroToCode/CodeMates6_Fall23#6]
## 💬 Work Stream 10/13
@austinschoff will focus on putting the recipe in the dinner section
@nicholascrh will enter in the needed information for instructions
@alpacapatata will approve the above requests 
Vivian will approve the requests as well and enter in the serving size and such

## ❗ Potential issues

Unsure if this is Nick Chen's correct handle and do not know Vivian's
## 👥 People to consult

@alpacapatata @nicholascrh @Vivian @jainaman93 
## 📃 Details

Text

**Comment by austinschoff** [comment]
@jainaman93 could you share Vivian Horvath's id with me?

**Comment by jainaman93** [comment]
@austinschoff : I do not have either the profile name or ID for Vivian.
